# Generated by Django 2.1.3 on 2018-12-09 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20181201_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
